USE javaqis;

-- LOGICAL OPERATORS
SELECT * FROM EMP WHERE DEPTNO=20;
SELECT ENAME,SAL FROM EMP WHERE SAL>1000;
SELECT * FROM EMP WHERE SAL%3=0;
SELECT * FROM EMP WHERE HIREDATE>='1981-1-1';
SELECT ENAME, DEPTNO, JOB FROM EMP WHERE DEPTNO=10;
SELECT ENAME, DEPTNO, JOB FROM EMP WHERE DEPTNO=10 AND JOB='MANAGER';
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE DEPTNO=20 AND SAL<3000;
SELECT * FROM EMP WHERE DEPTNO=20 OR DEPTNO=10;
SELECT ENAME, DEPTNO, JOB FROM EMP WHERE (DEPTNO=10 OR DEPTNO=20) AND JOB='MANAGER';
SELECT ENAME, DEPTNO, JOB FROM EMP WHERE (DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30) AND JOB='CLERK';
SELECT ENAME, DEPTNO, JOB FROM EMP WHERE DEPTNO IN (10,20,30) AND JOB='CLERK';
SELECT ENAME, DEPTNO, JOB, SAL FROM EMP WHERE (DEPTNO=20 OR DEPTNO=30) AND (JOB='CLERK' OR JOB='SALESMAN') AND SAL<1600;
SELECT * FROM DEPT WHERE NOT LOC='NEW YORK';

-- SPECIAL OPERATORS
SELECT * FROM EMP WHERE DEPTNO IN (10,20);
SELECT * FROM EMP WHERE DEPTNO NOT IN (10,20);
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 3000;
SELECT * FROM EMP WHERE deptno IN (10) AND hiredate BETWEEN '1982-1-1' AND '1982-12-31';
SELECT * FROM EMP WHERE deptno IN (10) AND hiredate NOT BETWEEN '1982-1-1' AND '1982-12-31';
SELECT ENAME, COMM FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE MGR IS NULL;
SELECT * FROM EMP WHERE MGR IS NOT NULL;
SELECT ENAME, COMM FROM EMP WHERE COMM IS NOT NULL;

-- LIKE
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '%S';
SELECT * FROM EMP WHERE ENAME LIKE '%C%';
SELECT * FROM EMP WHERE ENAME LIKE 'J%S';
SELECT * FROM EMP WHERE ENAME LIKE '_A%';
SELECT * FROM EMP WHERE ENAME LIKE '__R%';
SELECT * FROM EMP WHERE ENAME LIKE '__R%R';
SELECT * FROM EMP WHERE ENAME LIKE '%A%A%';
SELECT * FROM EMP WHERE ENAME LIKE '%R%R%';
SELECT * FROM EMP WHERE SAL LIKE '%50';
SELECT * FROM EMP WHERE HIREDATE LIKE '1981%';
SELECT * FROM EMP WHERE ENAME LIKE '_____';
SELECT * FROM EMP WHERE ENAME NOT LIKE '_____';